# Plugins
gems:             ['jekyll-gist']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            OSCP Notebook
# description:      "My collection of notes, commands, links, etc. when doing the Offensive Security Certified Professional (OSCP) Certification Lab"
# url:              https://tsondt.github.io/oscp
baseurl:          /oscp/

author:
  name:           'tsondt'
  url:            https://github.com/tsondt

repository:       tsondt/oscp

# Custom vars
version:          0.0.1

# github:
#   repo:           https://github.com/tsondt/oscp
